"""add_copy_version_extra

Revision ID: 0cd81009aa7d
Revises: e908b1616b27
Create Date: 2026-06-28 14:44:35.901275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0cd81009aa7d'
down_revision: Union[str, Sequence[str], None] = 'e908b1616b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copy_versions', sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('copy_versions', 'extra')
    # ### end Alembic commands ###
