"""rename_content_comments_relationship

Revision ID: 4099ccbfe84d
Revises: e7173fde7cfd
Create Date: 2026-06-28 12:04:22.745806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4099ccbfe84d'
down_revision: Union[str, Sequence[str], None] = 'e7173fde7cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('comments', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'comments')
    # ### end Alembic commands ###
