"""add_unique_constraints

Revision ID: e97c618755e4
Revises: cca292d7a186
Create Date: 2026-06-28 13:42:28.581509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e97c618755e4'
down_revision: Union[str, Sequence[str], None] = 'cca292d7a186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_content_platform', 'contents', ['project_id', 'platform', 'platform_content_id'])
    op.create_unique_constraint('uq_creator_platform', 'creators', ['project_id', 'platform', 'platform_creator_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_creator_platform', 'creators', type_='unique')
    op.drop_constraint('uq_content_platform', 'contents', type_='unique')
    # ### end Alembic commands ###
